### ISSUE TITLE
agent/inputs/placeholder.txt

### ISSUE THREAD

**Issue by mmcmurter-cribl** [sloan111/NodeEcosystsm#11]
I believe there should be a large events file at `agent/inputs/placeholder.txt` in your repo.  Was this a change you made or has something changed on our end?

**Comment by sloan111** [comment]
There should be!

Regrettably, the provided 1M_events file exceeds the 25MB size limit of the free GitHub tier.

**Comment by mmcmurter-cribl** [comment]
Ah, I see it's 25MB if uploaded via the browser.  Could you try pushing it from the command line when you get a chance?  No hurry.

**Comment by sloan111** [comment]
Yeah, that worked.

Here's the commit: https://github.com/sloan111/NodeEcosystsm/commit/a1d1aa1e6f6d1b348929d5d179aa72c55e21ed9e

**Comment by mmcmurter-cribl** [comment]
Thanks!
