### ISSUE TITLE
event_log newline addition

### ISSUE THREAD

**Issue by mmcmurter-cribl** [sloan111/NodeEcosystsm#12]
````
    event_log1 += '\n'  # ensure each log is newline terminated
    event_log2 += '\n'
````

This is modifying the source data.  Why do this and what are the potential issues that this may cause?

**Comment by sloan111** [comment]
It was found the the log files written by the target services were not newline terminated.  (May or may not be an actual issue, there are different schools of thought on this detail).

A newline is appended to the data set, so the the final (1 millionth) datum can be verified using the same mechanism as previous log entries.

The verification mechanism matches on complete lines (including newlines) to avoid an ambiguation where a search for "This is event number 2" could falsely match on "This is event number 200".

>potential issues that this may cause?

Right, so grooming source data for testing potentially sacrifices veracity for robustness, raising the risk of a false negative.  The real-world approach is discuss the file formatting with the application developer and potentially design testability into the application.
