### ISSUE TITLE
Events verification

### ISSUE THREAD

**Issue by denald** [sloan111/NodeEcosystsm#13]
In your current implementation you're heavily relying on event content, e.g. you're assuming  that `This is event number ` text is always present in event.
How would you change your implementation if events content is not known beforehand?

**Comment by sloan111** [comment]
Retrieve the contents of large_1M_events.log from the Agent service.  Then retrieve the contents of the event logs from the two target services as usual. Then apply the verification routine discussed in Issue #7:

-Open all 3 files for reading (does not load the whole file to RAM), save the 1st line of each file to separate working variable.
-Loop over entries in the test input data file where:
-If the current test data line matches the next line of either event log:
-Read the next line of the test data file, read the next line of the matching event log, continue the loop.
-If neither line matches, you have an error condition where that datum is either saved out-of-order or is missing.
-Pass if all you reach the end of all 3 files
