### ISSUE TITLE
Run the test after input file processed

### ISSUE THREAD

**Issue by denald** [sloan111/NodeEcosystsm#14]
Right now there is a big chance that the test would run before splitter is done sending all of the events (in case of larger files) Could this be avoided somehow?

**Comment by sloan111** [comment]
Yes, we found this actually occurs on some machines.

As discussed in Issue #3, this can be trivially solved by adding a sleep to the test code. A better implementation would be to poll the container list until the Agent finishes execution, then add a buffer sleep before retrieving the event logs.
