### ISSUE TITLE
Re: Workflow

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#15]
In your Workflow you are running `python environment_test.py`. So, it is just running the file (which does nothing). So, we get no test results when the Actions pipeline in run after a commit.

**Comment by sloan111** [comment]
Oh right, the CI test was going to be a no-op since I got stuck on the file size limit for the input data.

That's been fixed now so I can work on fixing the GitHub Action.

**Comment by sloan111** [comment]
OK it should be all working now:  https://github.com/sloan111/NodeEcosystsm/actions/runs/5357758154/jobs/9719137654

If you need to see more detailed test log output, there are some comical integration errors from test execution in the prior commits.

In case you're wondering why I didn't just invoke "pytest" initially, I was using the "python -m my_file.py" syntax locally as a workaround for a pytest path issue on a new dev setup.
