### ISSUE TITLE
Re: Target count

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#4]
Here:
```python
def test_logs(manage_services):
    event_log1 = read_file('assignment-target_1-1',
                           '/usr/src/app/events.log')  # container naming convention is different at this level than inside docker-compose
    event_log2 = read_file('assignment-target_2-1', '/usr/src/app/events.log')
```
How would you handle this if the number of targets was dynamic (assuming the `docker-compose.yml` adjusted accordingly)

**Comment by sloan111** [comment]
If the number of target services was dynamic, you can handle this by:

-constructing a get_targets() helper
-gets a list of running containers running_containers = client.containers.list()
-Loop over the list of containers and updates a target_container list if the container's .name attribute contains the text "target"
-returns the target container name list

Then, in your highlighted code section, call the get_targets() helper, and loop over each target container, retrieving the events log.
