### ISSUE TITLE
Re: Container names

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#5]
Here:
```python
def test_logs(manage_services):
    event_log1 = read_file('assignment-target_1-1',
                           '/usr/src/app/events.log')  # container naming convention is different at this level than inside docker-compose
    event_log2 = read_file('assignment-target_2-1', '/usr/src/app/events.log')
```
When I ran this, I had cloned the git repo to a local folder. I ran the test and it failed. Curious if you can tell me what happened and why hard-coding the names of the containers was the cause?

**Comment by sloan111** [comment]
>Curious if you can tell me what happened and why hard-coding the names of the containers was the cause?

I am assuming you mean the name matching on the container did not work for you.  If this was the case, there is a portability issue with the implementation, where you are likely using a different version/platform of Docker (Desktop) than I did in creating the solution.

A solution to this would to be to search containers containing "target" in the name string as discussed in Issue #4.

**Comment by smilinazzo** [comment]
When you clone the repo, it creates the repo in the folder: NodeEcosystem. And, since docker-compose up doesn't give a name for the project, the containers come up as `nodeecosystsm-target_1`.

**Comment by sloan111** [comment]
Oh wow.  As you've surely inferred, I've been running this from a folder called "assignment".

Let me know if you would like me to implement the fix described in this thread.
