### ISSUE TITLE
Re: Event count

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#6]
```python
    random_integers = [random.randint(2, 999999) for _ in range(98)]
    test_integers = [1, 1000000] + random_integers
```
How would you deal with an event file where the number of events was dynamic? Or at least, wasn't fixed to 1M.

**Comment by sloan111** [comment]
Of course, you always want to check for event #1 in boundary testing.

If the number of events isn't 1M, the test will need figure out what the maximum number is and test for that.  Without prior knowledge, one may need to loop over the Agent's events file to determine the last even number.
