### ISSUE TITLE
Re: Event search

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#7]
```python
    for test_num in test_integers:
        phrase = "This is event number " + str(test_num) + "\n"  # match newlines too, to avoid partial digit matches
        assert (phrase in event_log1) or (
                    phrase in event_log2)  # Verify that agent events are stored in 1 of the two targets

        if phrase in event_log1:  # Verify that splitter is not acting as a duplicator
            assert phrase not in event_log2
        else:
            assert phrase in event_log2
```
Is python `in` a linear search? Are we potentially searching a semi-large list `100x * 2`?

**Comment by sloan111** [comment]
Yes, it is a linear search.  This one reason why I'm only checking for sampling of the data set, instead of all 1 million test entries with this approach.

If you you know before hand that there is a guarantee events are written sequentially, you can achieve linear runtime by treating both logs as queues, checking the next entry of each log against the next test datum.

**Comment by smilinazzo** [comment]
I think the concern for checking all entries really only comes in to play when we reach 10s of millions of entries (at least with the memory allocation we have in github). How would you be able to check all entries without having to loop through the whole list multiple times?

**Comment by sloan111** [comment]
Right, so assuming you have access to the 1M_events (or bigger) test data file, and both events logs via Volumes (or similar mechanism), and assuming test data is sequential, you can search for all entries with a linear runtime and very little memory as follows:

-Open all 3 files for reading (does not load the whole file to RAM), save the 1st line of each file to separate working variable.
-Loop over entries in the test data file where:
   -If the current test data line matches the next line of either event log:
      -Read the next line of the test data file, read the next line of the matching event log, continue the loop.
   -If neither line matches, you have an error condition where that datum is either saved out-of-order or is missing.
   -Pass if all you reach the end of all 3 files
