### ISSUE TITLE
Re: Readfile

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#8]
```python
def read_file(service_name, file_name):
    container = client.containers.get(service_name)

    file_archive = container.get_archive(file_name)
    stream, stat = file_archive
    file_obj = BytesIO()
    for i in stream:
        file_obj.write(i)
    file_obj.seek(0)
    tar = tarfile.open(mode='r', fileobj=file_obj)
    text = tar.extractfile('events.log')
    return text.read().decode('utf-8')
```
Is there potentially another way to do this where we aren't storing a _large_ file in memory all at once?

**Comment by sloan111** [comment]
You can prevent loading the whole file at once, but retrieving it in chunks, for example remotely running the command:

awk 'NR>=1000{print}NR==2000{exit}' /usr/src/app/events.log

**Comment by smilinazzo** [comment]
You could also use a generator. Opening the file and reading a single line at a time. Checking for that line and then moving to the next.
