### ISSUE TITLE
Re: ReadLogs

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#9]
```python
def read_logs(service_name):  # container-level logs
    print(f"Reading logs from {service_name}...")
    container = client.containers.get(service_name)
    print(str(container))
    logs = container.logs(stdout=True, stderr=False)  # 1st, cut
    # container-level log gives output like 'My hostname is: a9d3519b71f0\nworking as target\noutputfile events.log\nApp listening on port 9997\nclient connected\n'
    return logs.decode('utf-8')
```
I didn't see where this was being used. I'm assuming for collecting artifacts after the tests?

**Comment by sloan111** [comment]
That correct that is not being used.

I initially wrote this helper to retrieve the container logs before realizing another approach was needed to get events.log off the file system.  While this is a small example, in a larger framework, I would leave this helper in a utility for later use.
